config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#top"
  get "/about", to: "home#about"
  get "signup", to: "users#new"
  get "/info", to: "home#info"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
  def info
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<%= provide(:title, "About")%>
<br><br><br><br><br><br><br><br>

<h1>Hello#world</h1>
<p>Find me in app/views/hello/world.html.erb</p>

app/views/home/info.html.erb
<div class="top">
      <h1 id= "use_1">Darts Markとは</h1>
      <p>・ダーツを通して色んな人と出会い、繋がることを目指したサイトです。</p>
      <p>・お互いに評価し合うことで初めて合う人でも心配ありません。</p>
      <p>・空いた時間にダーツ友達の輪を広げましょう。</p>
      <p>・掲示板を使いダーツの雑談を楽しんでください。</p>

    <div class="use">
      <h2 id ="use_2">使い方</h2>
      <p>・ユーザー登録しましょう。</p>
      <p>・地域を設定をしましょう。</p>
      <p>・友達を募集か参加し連絡を取り合いましょう。</p>
      <p>・終わったらお互いを評価してください。次の出会いに繋がります。</p>

    </div>

    </div>

app/views/home/top.html.erb
<% provide(:title, 'Top') %>
<div class="main-container">
  <div class="main-container-top">

    <h1>Make A New Friends</h1>
    <div class="main-btn">
      <%= link_to("募集する", "#",{class: "request"}) %>
      <%= link_to("みつける", "#",{class: "find"}) %>
      <%= link_to("掲示板", "#", {class: "bbs"})%>

    </div>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-footer">
    <%= link_to("Darts Mark", "/") %>
    <a href="#" class = "btn kiyaku">利用規約</a>
    <a href="#" class = "btn kiyaku">プライバシー</a>

  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="header-left">
      <%= link_to("Darts Mark", "/") %>
    </div>
  </div>
  <div class="header-right">
    <%= link_to("ユーザー登録", signup_path, class: "btn btn-lg btn-primary") %>
  </div>
  <div class="header-right1">
    <%= link_to("ログイン", "#") %>
  </div>
  <div class="header-left1">
    <%= link_to("Darts Markとは", about_path) %>
    <%= link_to("使い方", info_path) %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mysite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>